### ISSUE TITLE
conda installation is not successful

### ISSUE THREAD

**Issue by JunCEEE** [lucagelisio/cfelpyutils#6]
Tried to install cfelutils via conda: `conda install -c ondateam cfelpyutils`, but failed:
```
UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: ondateam
  channel url: https://conda.anaconda.org/ondateam
  error code: 404
```
Maybe the README.md needs to be updated?

**Comment by lucagelisio** [comment]
Thank you very much, README.md has been updated!
